
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/layout/ResponsiveNav";
import Footer from "@/components/sections/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import Whatsap from "@/components/social/Whatsap";
import Script from "next/script"; // ✅ Import Next.js Script

const font = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kijichi | Gateway | Hotel",
  description: "Generated by Kijichi Gateway Hotel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased relative`}>
        {/* ResponsiveNav is fixed, overlays content */}
        <ResponsiveNav />

        {/* Main content padding to avoid overlap with nav */}
        <main className="pt-[80px]"> {/* adjust 80px according to nav height */}
          {children}
        </main>

        <Footer />
        <Whatsap />
        <ScrollToTop />

        {/* ✅ Tawk.to Script */}
        <Script id="tawk-to" strategy="afterInteractive">
          {`
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
              var s1=document.createElement("script"),
              s0=document.getElementsByTagName("script")[0];
              s1.async=true;
              s1.src='https://embed.tawk.to/68ac4b03891afb1924e0607e/1j3gga1uu';
              s1.charset='UTF-8';
              s1.setAttribute('crossorigin','*');
              s0.parentNode.insertBefore(s1,s0);
            })();
          `}
        </Script>
      </body>
    </html>
  );
}
